services:
  - type: web
    name: gophish
    env: docker
    plan: starter
    region: oregon
    healthCheckPath: /
    envVars:
      - key: GIN_MODE
        value: release
      - key: PORT
        value: 3333
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeploy: true
    branch: master
