services:
  - type: web
    name: gophish
    env: docker
    plan: starter
    region: oregon
    healthCheckPath: /login
    envVars:
      - key: GIN_MODE
        value: release
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeploy: true
    branch: master
